name: Build for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/checkout@v3
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=12.2

    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies with dotnet restore
      run: dotnet restore

    - name: Restore dependencies with nuget restore
      run: nuget restore

    - name: Build
      run: /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono '/Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/MSBuild.dll' Vulcanova/Vulcanova.Android/Vulcanova.Android.csproj /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: Vulcanova/Vulcanova.Android/bin/Release/io.github.vulcanova-Signed.apk
